# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 00:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_agregado_modelo_componente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componente',
            name='firma',
            field=models.CharField(blank=True, max_length=1500, null=True, verbose_name='Firma Electronica'),
        ),
    ]
