# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 18:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0003_corregida_firma_componente'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComponenteAuditoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField(verbose_name='Contenido')),
                ('firma', models.TextField(verbose_name='Firma Electrónica')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('descripcion', models.TextField(verbose_name='Descripcion')),
                ('accion', models.SmallIntegerField(choices=[(1, 'Creado'), (2, 'Editado'), (3, 'Eliminado')], verbose_name='Accion')),
                ('componente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pistas_auditoria', to='main.Componente', verbose_name='Componente')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='componentes_auditoria', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Auditoria de Componente',
                'verbose_name_plural': 'Auditoria de Componentes',
            },
        ),
    ]
